/**
 * ui/components/CommentaryLog.js — casted play-by-play feed (P12.7).
 * Pure props -> VNode. Renders reverse-chronological commentary lines for the
 * rounds revealed so far (n <= cursor), newest round on top, so the latest action
 * is always visible without scrolling (no DOM auto-scroll needed). Lines are
 * generated by engine/match/commentary.js from the data the engine already logs.
 */

import { h, classNames } from '../render.js';
import { roundCommentary } from '../../engine/match/commentary.js';

/**
 * @param {object} props
 * @param {object} props.mapResult           a MapResult { rounds, score }
 * @param {Record<string,object>} props.playersById
 * @param {Record<string,object>} props.teamsById
 * @param {string} props.teamAId
 * @param {string} props.teamBId
 * @param {number} [props.index]   reveal cursor (highest round revealed); default = all
 * @param {boolean} [props.playing]
 * @returns {import('../render.js').VNode}
 */
export function CommentaryLog(props) {
  const { mapResult, playersById = {}, teamsById = {}, teamAId, teamBId, index, playing = false } = props || {};
  const rounds = (mapResult && mapResult.rounds) || [];
  const score = (mapResult && mapResult.score) || { A: 0, B: 0 };
  const total = (score.A || 0) + (score.B || 0);
  const cursor = typeof index === 'number' ? index : total;
  const ctx = { players: playersById, teamsById, teamAId, teamBId };

  // Revealed rounds, newest first. While paused at the end, show everything.
  const shown = rounds.filter((r) => (playing ? r.n <= cursor : true));
  if (shown.length === 0) {
    return h('div', { class: 'commentary commentary--empty muted' }, 'Press play to follow the action.');
  }

  const blocks = [];
  for (let i = shown.length - 1; i >= 0; i -= 1) {
    const r = shown[i];
    const lines = roundCommentary(r, ctx);
    // Within a round, show the result line first (it's the latest beat).
    for (let j = lines.length - 1; j >= 0; j -= 1) {
      const ln = lines[j];
      blocks.push(
        h(
          'div',
          { key: `c-${r.n}-${j}`, class: classNames('commentary__line', `commentary__line--${ln.tone}`, ln.team && `commentary__line--team${ln.team}`) },
          h('span', { class: 'commentary__rd' }, `R${r.n}`),
          h('span', { class: 'commentary__txt' }, ln.text)
        )
      );
    }
  }

  return h(
    'div',
    { class: 'commentary' },
    h('h3', { class: 'commentary__title' }, '📣 Play-by-play'),
    h('div', { class: 'commentary__feed' }, ...blocks)
  );
}
